TRUNCATE TABLE mining.StarSystemLocation 

INSERT INTO mining.StarSystemLocation ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', '',  'Aaron Halo')

INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Mining Base #IGB-FXW')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Mining Base #BBR-4JQ')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Mining Base #365-YNZ')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Mining Base #WUO-ZRU')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Mining Base #6IN-PO2')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Mining Base #LBP-UN5')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Mining Base #ODD-E9B')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Mining Base #R08-Y3K')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Mining Base #7LI-0OA')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Mining Base #YTO-GLQ')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Mining Base #01K-I43')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'HUR L1')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'HUR L2')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'HUR L3')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'HUR L4')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'HUR L5')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Aberdeen')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Arial')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Ita')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode]) VALUES ('STANTON', 'Hurston', 'Magda')

INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #5U5-TLC')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #XJZ-JR2')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #Q9Q-090')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #X92-IVA')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #JUG-0KZ')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #R7J-WJ7')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #SAG-2UN')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #U5X-NGQ')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #UDK-IJX')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #AL5-XPD')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #RCD-0B3')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #G04-CH0')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #1XA-3GI')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Mining Base #CVF-T6H')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'MIC L1')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'MIC L2')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'MIC L3')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'MIC L4')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'MIC L5')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Calliope')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Clio')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Mircotech', 'Euterpe')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #4R0-NVX')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #0YX-07Z')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #OYV-JKE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #8CG-OSA')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #RSV-8HL')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #CZW-RRY')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #7YH-JX7')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #8PV-WNE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #BSK-IJ5')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #A73-HTJ')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #74H-2DO')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #BRE-582')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #7IQ-29Q')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Mining Base #N6J-XKH')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'ARC L1')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'ARC L2')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'ARC L3')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'ARC L4')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'ARC L5')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Lyria')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'ArcCorp', 'Wala')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Mining Base #IO3-H1F')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Mining Base #E38-S5G')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Mining Base #W79-2H7')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Mining Base #4PI-3YY')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Mining Base #R75-5PZ')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Mining Base #QXS-NBS')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Mining Base #UU6-1EI')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Mining Base #Q4U-I20')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Mining Base #URB-H3V')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Mining Base #51F-OGH')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Mining Base #Z48-013')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'CRU L1')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'CRU L2')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'CRU L3')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'CRU L4')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'CRU L5')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Daymar')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Cellin')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Yela')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('STANTON', 'Crusader', 'Yela Belt')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'Pyro I')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'RMB-SURD')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'RMB-ONER')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'RMB-KAIN')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'RMB-MYAL')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'RMB-BALM')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'RMB-PURI')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'PYR1 L1')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'PYR1 L2')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'PYR1 L3')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'PYR1 L4')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'RMB-IKAN')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'RMB-VOES')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'RMB-DREG')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'PYR1 L5')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'RMB-BALE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'RMB-RIGG')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro I', 'RMB-CEDI')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'RMB-SHEW')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'RMB-NIGH')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'RMB-ZARF')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'RMB-GREX')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'RMB-ELMS')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'RMB-EVEN')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'RMB-LAZO')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'RMB-NAIN')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'PYR2 L1')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'PYR2 L2')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'PYR2 L3')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'PYR2 L4 - Checkmate')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'PYR2 L5 - RMB-LIRE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'PYR2 L5 - RMB-HOWE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Monox', 'PYR2 L5 - RMB-TIAN')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'PYR3 L1 - Starlight Service Station')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'RMB-TACK')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'RMB-LEST')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'RMB-JONG')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'RMB-KNAP')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'RMB-OXID')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'PYR3 L2')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'RMB-BASK')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'RMB-HELM')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'RMB-PALL')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'RMB-AXIL')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'RMB-BUCK')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'PYR3 L3 - Patch City')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'PYR3 L4')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Bloom', 'PYR3 L5')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro V', 'Pyro V')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro V', 'RMB-SIJO')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro V', 'PYR5 L1')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro V', 'PYR5 L1 - RMB-NARY')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro V', 'PYR5 L1 - RMB-TYRO')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro V', 'PYR5 L1 - RMB-JUTE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro V', 'PYR5 L2 - Gaslight')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro V', 'PYR5 L2 - Gaslight - RMB-OLLA')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro V', 'PYR5 L2 - Gaslight - RMB-MURK')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro V', 'PYR5 L2 - Gaslight - RMB-SPAW')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro V', 'PYR5 L3')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro V', 'PYR5 L4')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro V', 'PYR5 L5 - Rat''s Nest')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'Pyro IV')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'Pyro 4 Rings')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'RMB-ARID')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'RMB-NONG')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'RMB-HADE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'Ignis')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'RMB-RINE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'RMB-ALME')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'RMB-LYES')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'Vatra')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'Adir')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'Fairo')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'Fuego')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'RMB-OAKS')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Pyro IV', 'Vuur')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'Terminus')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-NENE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-JADE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-KELT')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-RAIK')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-RAWN')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-SEER')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-MARA')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-QINS')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-MOSK')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-ION')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-PIZE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-LOWN')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-CRUE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-HARK')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-SOWL')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-UMUS')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'RMB-MEFF')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Terminus', 'Terminus Rings')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'PYR6 L1', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'PYR6 L2', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'PYR6 L3 - Endgame', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'PYR6 L4 - Dudley & Daughters', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'PYR6 L5 - Megumi Refueling', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster BGR-560', 'RMB-GRAY')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster BGR-560', 'RMB-MAGE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster BGR-560', 'RMB-GADE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster BGR-560', 'RMB-WARB')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster BGR-560', 'RMB-DARI')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster BGR-560', 'RMB-LUNE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster CAJ-445', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster CAJ-445','RMB-HORN')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster CAJ-445','RMB-PEKE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster CAJ-445','RMB-MUGG')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster CAJ-445','RMB-KIFF')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster CAJ-445','RMB-YEAD')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster DLO-486' ,'')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster DLO-486' ,'RMB-DIRK')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster DLO-486' ,'RMB-PLEX')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster DLO-486' ,'RMB-TIGS')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster DLO-486' ,'RMB-SAIC')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster EMM-567', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster FSN-704', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster GRP-839', 'RMB-LANX')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster HJS-232', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster JWY-925', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster KKE-717', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster KKE-717' ,'RMB-VERD')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RMB-FLAG', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RMB-BORS', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster LHB-976', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster MNK-833', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster NBD-102', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster RSC-340', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster RSC-340', 'RMB-KYUS')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster RSC-340', 'RMB-DORY')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster RSC-340', 'RMB-RODE')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster WDH-387', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'Cluster YKA-011', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'PYAM-EXHANG-0-1', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'PYAM-SUPVISR-3-4', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'PYAM-SUPVISR-3-5', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-ALPHA', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-BRAVO', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-CHARLIE', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-COOK', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-DELTA', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-ECHO', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-FOXTROT', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-GULF', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-HELIO', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-IGNITION', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-ION', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-JAK', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-KILO', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-LAMDA', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-LYNX', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-MAT', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-NOVEMBER', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-OVER', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-POINT', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-QUAGMIRE', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-ROTH', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-SIERRA', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-TUNG', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-ULTRA', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-VICTORY', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-WHISKEY', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-XENO', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-YORK', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('PYRO', 'RAB-ZETA', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('Nyx', '', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('Nyx', 'Glaciem Ring', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('Nyx', 'Nyx I', '')
INSERT INTO mining.StarSystemLocation  ([SystemCode], [SubSystemCode], [LocationCode])VALUES ('Nyx', 'Nyx II', '')