CREATE TABLE [dbo].[Vehicles]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	VehicleName VARCHAR(40),
    Manufacturer VARCHAR(60),
    VehicleRole VARCHAR(40),
    Career VARCHAR(40),
    Size CHAR(4),
    CrewSizeMin INT,
    CrewSizeMax INT,
    ScmSpeed INT,
    ScmBoostForward INT,
    ScmBoostBackward INT,
	NavMax INT,
    Pitch INT,
    Yaw INT,
    Roll INT,
    BoostedPitch INT,
    BoostedYaw INT,
    BoostedRoll INT,
	PowerConsumption INT,
	CMDecoyCount INT,
    CMNoiseCount INT,
    HitPoints INT,
	CargoSize INT,
	VehicleLength FLOAT,
    VehicleWidth FLOAT,
    VehicleHeight FLOAT,
    VehicleMass INT,
    HydrogenTank FLOAT,
    QuantiumTank FLOAT,
	ClaimTimeInSeconds INT,
	ExpediteTimeInSeconds INT,
    ExpediteCost INT,
	Pledged BIT,
    InGame BIT,
)
